name: make-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
        type: string

jobs:
  create-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build NetBlame addin
        run: |
          dotnet build  src\NetBlame\NetBlameAddIn.sln --configuration Release -p:Version=${{ inputs.version }}
        shell: cmd

      - name: Create ZIP archive with all scripts and binaries
        shell: pwsh
        run: make\CreateRelease.ps1 -NetBlameBuild "src\NetBlame\bin\Release\net8.0" -WorkingDir bin -OutputZip "bin\MSO-Scripts-${{ inputs.version }}.zip"

      - name: Publish release
        run: gh release create version_${{ inputs.version }} --title "Release ${{ inputs.version }}" "bin\MSO-Scripts-${{ inputs.version }}.zip" --notes "Manual release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
